language: java
sudo: false
dist: trusty
cache:
    directories:
        - $HOME/.m2
script:
    - mvn clean install --errors --batch-mode
env:
    global:
        - MAVEN_OPTS="-Xmx256m"
        - JAVA_OPTS="-Xmx256m"
jdk:
    - oraclejdk11
